### ISSUE TITLE
trimaps need when it is no selection?

### ISSUE THREAD

**Issue by caihaunqai** [Fire-friend/dugMatting#1]
Hello, I wonder if the trimap is needed in the experiments on Matteformer and MGMatting. I observe that the mse is quite low when it is without Selection. If no selection means the input is just RGB image, it's kind of a shock to me.

<img width="1172" alt="image" src="https://github.com/Fire-friend/dugMatting/assets/56779804/1c098059-a807-4353-8128-e7090305f653">

**Comment by Fire-friend** [comment]
Trimaps are not necessary. In our experiment, we used their pre-trained model of their method to accelerate the trainning process. Besides, many auto-matting techniques have been successful in automatically extracting objects of interest from the Composition-1K dataset.

**Comment by caihaunqai** [comment]
> Trimaps are not necessary. In our experiment, we used their pre-trained model of their method to accelerate the trainning process. Besides, many auto-matting techniques have been successful in automatically extracting objects of interest from the Composition-1K dataset.

Thank you for your reply. Prior-token(which indeed is trimap) is used in MatteFormer, do you also remove it? Thank you.

**Comment by Fire-friend** [comment]
We compute it based on the randomly generated user map.

**Comment by caihaunqai** [comment]
Thank you.
